export const RISK_LEVELS = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
export const RISK_STATUSES = ["IDENTIFIED", "ASSESSED", "MITIGATION_IN_PROGRESS", "MONITORED", "CLOSED"];
export const MITIGATION_PLAN_STATUSES = ["PLANNED", "IN_PROGRESS", "COMPLETED", "CANCELLED", "OVERDUE"];
export const MITIGATION_ACTION_STATUSES = ["PENDING", "IN_PROGRESS", "COMPLETED", "CANCELLED"];
export const ROLES = { ADMIN: "ADMIN", RISK_MANAGER: "RISK_MANAGER", ANALYST: "ANALYST", VIEWER: "VIEWER" };
export const SCALE_OPTIONS = [1, 2, 3, 4, 5];